# Generated by Django 3.0.7 on 2020-07-25 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodStall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyNUS.Cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Comment', models.TextField()),
                ('Rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Boring'), (3, 'Good'), (4, 'Great'), (5, 'Excelent')])),
                ('foodstall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyNUS.FoodStall')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=15)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyNUS.Cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='foodstall',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyNUS.Location'),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='menu', to='yummyNUS.Menu'),
        ),
    ]
