# Generated by Django 3.0.7 on 2020-07-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummyNUS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='foodstall',
            new_name='Foodstall',
        ),
    ]
