# Generated by Django 3.0.7 on 2020-07-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummyNUS', '0003_auto_20200726_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstall',
            name='review',
        ),
        migrations.AddField(
            model_name='foodstall',
            name='review',
            field=models.ManyToManyField(blank=True, to='yummyNUS.Review'),
        ),
    ]
